/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FormsIndexRouteImport } from './routes/_forms/index'
import { Route as ProtectedBoardsRouteImport } from './routes/_protected/boards'
import { Route as FormsSignUpRouteImport } from './routes/_forms/sign-up'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ProtectedBoardBoardIdRouteImport } from './routes/_protected/board/$boardId'

const FormsIndexRoute = FormsIndexRouteImport.update({
  id: '/_forms/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedBoardsRoute = ProtectedBoardsRouteImport.update({
  id: '/_protected/boards',
  path: '/boards',
  getParentRoute: () => rootRouteImport,
} as any)
const FormsSignUpRoute = FormsSignUpRouteImport.update({
  id: '/_forms/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedBoardBoardIdRoute = ProtectedBoardBoardIdRouteImport.update({
  id: '/_protected/board/$boardId',
  path: '/board/$boardId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/sign-up': typeof FormsSignUpRoute
  '/boards': typeof ProtectedBoardsRoute
  '/': typeof FormsIndexRoute
  '/board/$boardId': typeof ProtectedBoardBoardIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/sign-up': typeof FormsSignUpRoute
  '/boards': typeof ProtectedBoardsRoute
  '/': typeof FormsIndexRoute
  '/board/$boardId': typeof ProtectedBoardBoardIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_forms/sign-up': typeof FormsSignUpRoute
  '/_protected/boards': typeof ProtectedBoardsRoute
  '/_forms/': typeof FormsIndexRoute
  '/_protected/board/$boardId': typeof ProtectedBoardBoardIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/sign-up' | '/boards' | '/' | '/board/$boardId' | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to: '/sign-up' | '/boards' | '/' | '/board/$boardId' | '/api/auth/$'
  id:
    | '__root__'
    | '/_forms/sign-up'
    | '/_protected/boards'
    | '/_forms/'
    | '/_protected/board/$boardId'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  FormsSignUpRoute: typeof FormsSignUpRoute
  ProtectedBoardsRoute: typeof ProtectedBoardsRoute
  FormsIndexRoute: typeof FormsIndexRoute
  ProtectedBoardBoardIdRoute: typeof ProtectedBoardBoardIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_forms/': {
      id: '/_forms/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof FormsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/boards': {
      id: '/_protected/boards'
      path: '/boards'
      fullPath: '/boards'
      preLoaderRoute: typeof ProtectedBoardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_forms/sign-up': {
      id: '/_forms/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof FormsSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/board/$boardId': {
      id: '/_protected/board/$boardId'
      path: '/board/$boardId'
      fullPath: '/board/$boardId'
      preLoaderRoute: typeof ProtectedBoardBoardIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  FormsSignUpRoute: FormsSignUpRoute,
  ProtectedBoardsRoute: ProtectedBoardsRoute,
  FormsIndexRoute: FormsIndexRoute,
  ProtectedBoardBoardIdRoute: ProtectedBoardBoardIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
